CREATE DATABASE catalogoFilmes_db;

USE catalogoFilmes_db;

CREATE TABLE TB_USUARIO(
	ID_USUARIO 		INT PRIMARY KEY AUTO_INCREMENT,
    NM_USUARIO 		VARCHAR(200),
    DS_EMAIL 		VARCHAR(200),
    DS_SENHA 		VARCHAR(20)
);

CREATE TABLE TB_FILME(
	ID_FILME 		INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO 		INT,
    NM_FILME 		VARCHAR(200),
    DS_SINOPSE 		VARCHAR(4000),
    VL_AVALIACAO 	DECIMAL(15,2),
    DT_LANCAMENTO 	DATE,
    BT_DISPONIVEL 	BOOLEAN, 
    IMG_FILME 		VARCHAR(800),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
);